#!/usr/bin/env bash
# Generate Ed25519 keypairs for dupenet services and write .env.local.
# Run once before first docker compose up.
#
# Usage: ./scripts/gen-keys.sh
#
# Produces: .env.local (gitignored)

set -euo pipefail

OUTFILE=".env.local"

if [ -f "$OUTFILE" ]; then
  echo "⚠  $OUTFILE already exists. Delete it first to regenerate."
  exit 1
fi

echo "Generating Ed25519 keypairs..."

# Use Node.js Web Crypto to generate keypairs (same as @dupenet/physics)
KEYS=$(node --input-type=module <<'KEYGEN'
async function genKeypair() {
  const kp = await crypto.subtle.generateKey("Ed25519", true, ["sign", "verify"]);
  const pubRaw = new Uint8Array(await crypto.subtle.exportKey("raw", kp.publicKey));
  const privPkcs8 = new Uint8Array(await crypto.subtle.exportKey("pkcs8", kp.privateKey));
  const privRaw = privPkcs8.slice(-32);
  const toHex = (b) => [...b].map(x => x.toString(16).padStart(2, "0")).join("");
  return { pub: toHex(pubRaw), sk: toHex(privRaw) };
}

const host  = await genKeypair();
const mint1 = await genKeypair();
const mint2 = await genKeypair();
const mint3 = await genKeypair();

console.log(JSON.stringify({ host, mint1, mint2, mint3 }));
KEYGEN
)

HOST_PUB=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.host.pub)")
HOST_SK=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.host.sk)")
MINT1_PUB=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.mint1.pub)")
MINT1_SK=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.mint1.sk)")
MINT2_PUB=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.mint2.pub)")
MINT2_SK=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.mint2.sk)")
MINT3_PUB=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.mint3.pub)")
MINT3_SK=$(echo "$KEYS" | node -e "const k=JSON.parse(require('fs').readFileSync(0,'utf8'));process.stdout.write(k.mint3.sk)")

cat > "$OUTFILE" <<EOF
# Generated by scripts/gen-keys.sh — DO NOT COMMIT
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Host identity (gateway + node-agent)
HOST_PUBKEY=${HOST_PUB}
AGENT_HOST_PRIVATE_KEY_HEX=${HOST_SK}
AGENT_HOST_ENDPOINT=http://localhost:80

# Mint 1 (used by compose-founder.yml)
MINT1_SK_HEX=${MINT1_SK}
MINT1_PUB_HEX=${MINT1_PUB}

# Mint 2 (spare — run a second mint service if desired)
MINT2_SK_HEX=${MINT2_SK}
MINT2_PUB_HEX=${MINT2_PUB}

# Mint 3 (spare)
MINT3_SK_HEX=${MINT3_SK}
MINT3_PUB_HEX=${MINT3_PUB}

# Coordinator: comma-separated trusted mint public keys
MINT_PUBKEYS=${MINT1_PUB},${MINT2_PUB},${MINT3_PUB}

# Pricing defaults
MIN_REQUEST_SATS=3
SATS_PER_GB=500
EOF

echo "✓ Written to $OUTFILE"
echo ""
echo "  HOST_PUBKEY:  ${HOST_PUB}"
echo "  MINT1 pubkey: ${MINT1_PUB}"
echo "  MINT2 pubkey: ${MINT2_PUB}"
echo "  MINT3 pubkey: ${MINT3_PUB}"
echo ""
echo "Next: docker compose -f deploy/compose-founder.yml --env-file .env.local up --build"
